// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.HopeThisWorksPDP;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon chassisleftMotor;
    public static CANTalon chassisrightMotor;
    public static RobotDrive chassisRobotDrive2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisleftMotor = new CANTalon(0);
        LiveWindow.addActuator("chassis", "leftMotor", chassisleftMotor);
        
        chassisrightMotor = new CANTalon(1);
        LiveWindow.addActuator("chassis", "rightMotor", chassisrightMotor);
        
        chassisRobotDrive2 = new RobotDrive(chassisleftMotor, chassisrightMotor);
        
        chassisRobotDrive2.setSafetyEnabled(true);
        chassisRobotDrive2.setExpiration(0.1);
        chassisRobotDrive2.setSensitivity(0.5);
        chassisRobotDrive2.setMaxOutput(1.0);
        chassisRobotDrive2.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
