// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3588.Steamworks;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static CANTalon chassisLeftFrontMotor;
	public static CANTalon chassisLeftRearMotor;
	public static CANTalon chassisRightFrontMotor;
	public static CANTalon chassisRightRearMotor;
	public static RobotDrive chassisRobotDrive;
	public static CANTalon climbingMotor;
	public static DigitalInput climbinglimitSwitch;
	public static CANTalon climbingLeftSweeper;
	public static CANTalon climbingRightSweeper;
	public static Encoder climbingLeftRopeEncoder;
	public static Encoder climbingRightRopeEncoder;
	public static DoubleSolenoid gearsSolenoid;
	public static DigitalInput gearslineBreak;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static ADXRS450_Gyro chassisGyro;

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		chassisLeftFrontMotor = new CANTalon(1);
		LiveWindow.addActuator("Chassis", "LeftFrontMotor", chassisLeftFrontMotor);

		chassisLeftRearMotor = new CANTalon(2);
		LiveWindow.addActuator("Chassis", "LeftRearMotor", chassisLeftRearMotor);

		chassisRightFrontMotor = new CANTalon(3);
		LiveWindow.addActuator("Chassis", "RightFrontMotor", chassisRightFrontMotor);

		chassisRightRearMotor = new CANTalon(0);
		LiveWindow.addActuator("Chassis", "RightRearMotor", chassisRightRearMotor);

		chassisRobotDrive = new RobotDrive(chassisLeftFrontMotor, chassisLeftRearMotor, chassisRightFrontMotor,
				chassisRightRearMotor);

		chassisRobotDrive.setSafetyEnabled(true);
		chassisRobotDrive.setExpiration(0.1);
		chassisRobotDrive.setSensitivity(0.5);
		chassisRobotDrive.setMaxOutput(1.0);
		chassisRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
		chassisRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
		climbingMotor = new CANTalon(4);
		LiveWindow.addActuator("Climbing", "Motor", climbingMotor);

		climbinglimitSwitch = new DigitalInput(0);
		LiveWindow.addSensor("Climbing", "limitSwitch", climbinglimitSwitch);

		climbingLeftSweeper = new CANTalon(5);
		LiveWindow.addActuator("Climbing", "LeftSweeper", climbingLeftSweeper);

		climbingRightSweeper = new CANTalon(6);
		LiveWindow.addActuator("Climbing", "RightSweeper", climbingRightSweeper);

		climbingLeftRopeEncoder = new Encoder(6, 7, false, EncodingType.k4X);
		LiveWindow.addSensor("Climbing", "LeftRopeEncoder", climbingLeftRopeEncoder);
		climbingLeftRopeEncoder.setDistancePerPulse(1.0);
		climbingLeftRopeEncoder.setPIDSourceType(PIDSourceType.kRate);
		climbingRightRopeEncoder = new Encoder(8, 9, false, EncodingType.k4X);
		LiveWindow.addSensor("Climbing", "RightRopeEncoder", climbingRightRopeEncoder);
		climbingRightRopeEncoder.setDistancePerPulse(1.0);
		climbingRightRopeEncoder.setPIDSourceType(PIDSourceType.kRate);
		gearsSolenoid = new DoubleSolenoid(0, 0, 1);
		LiveWindow.addActuator("Gears", "Solenoid", gearsSolenoid);

		gearslineBreak = new DigitalInput(1);
		LiveWindow.addSensor("Gears", "lineBreak", gearslineBreak);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		chassisGyro = new ADXRS450_Gyro();
	}
}
