// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.Steamworks.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc3588.VisionTester.RobotMap;
import org.usfirst.frc3588.VisionTester.Robot;

/**
 *
 */
public class DriveCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	RobotMap.chassisRobotDrive.mecanumDrive_Cartesian(Robot.oi.joystick.getX(), Robot.oi.joystick.getY(), Robot.oi.joystick.getTwist(), 0.0);
    	RobotMap.chassisRobotDrive.setMaxOutput(1-Robot.oi.joystick.getThrottle());
    	
    	if(Robot.oi.joystick.getPOV() == 270) {
    		RobotMap.chassisRobotDrive.mecanumDrive_Cartesian(-1, 0, 0, 0);
    	}
    	else if(Robot.oi.joystick.getPOV() == 180) {
    		RobotMap.chassisRobotDrive.mecanumDrive_Cartesian(0, .5, 0, 0);
    	}
    	else if(Robot.oi.joystick.getPOV() == 90) {
    		RobotMap.chassisRobotDrive.mecanumDrive_Cartesian(1, 0, 0, 0);
    	}
    	else if(Robot.oi.joystick.getPOV() == 0) {
    		RobotMap.chassisRobotDrive.mecanumDrive_Cartesian(0, -.5, 0, 0);
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
